### PR TITLE
Feature: More precise disk evaluation with conversion from bytes into human readable format

### PR DESCRIPTION
**Pull request by luddinho**
Evaluate the size in 1 byte blocks and convert values into human-readable format for a more precise reported number with 2 decimal points.

Refactor: 
Added library function for conversion from bytes into human-readable format.
Added library function for the disk size evaluation.

Minor maintenance adaptions.

### CODE REVIEW

**Comment by toafez** [comment]
Hi!

I haven't looked at your changes yet. But could you perhaps move the files ui/lib/**bytes2human.sh** and ui/lib/**eval_disk_space.sh** to the **ui/modules** folder and adjust the changed paths in ui/execute.sh and ui/main.sh accordingly. There are already some functions in the ui/modules folder, so I would like to see your changes here.

That would be really great

**Comment by luddinho** [comment]
Hi, yes for sure.

Honestly my initial approach was to use the ui/modules directory for those files. But I did not see the affiliation with that folder name and I decided to create a lib folder instead.

However, I will respect your project setup, and therefore I have done the changes as requested with the latest commit bc450e9.

I hope this meets your expectations.

**Comment by toafez** [comment]
Thank you for your adjustments. I'll have a look tomorrow. Anyway, in the end it's just names. The /lib folder name would fit and I might give a thought to moving all the function files there. For now, two folders are just too much for me, but I will think about changing it.

**Comment by toafez** [comment]
I've taken a look at your customizations and I'm really impressed. It looks perfect. Many thanks for your great code snippets

**Pull request merged**
